processors:
  IdProcessor:
    class_name: IdProcessor
    module_path: common.processors.base_processor
    config:
  TextProcessor:
    class_name: TextProcessorPrompt
    module_path: ccac.processors.ccac_processor
    config:
      path: /root/autodl-tmp/model/ccac/track2/mengzi
      input_max_length: 32
      output_max_length: 256
      add_angle: true
      val_angles:
      - 定义
      - 反驳
      - 影响
      - 背景
      - 举例

dataset:
  class_name: CcacDataset
  module_path: ccac.datasets.ccac_dataset
  datasets:
    train:
      dataset_type: train
      data_root_dir: /root/autodl-tmp/data/ccac/track2/angle/
      data_file_path: 
      - train_data.json
      processor_ids:
      - IdProcessor
      - TextProcessor
      use_argument_cls: true
    val:
      dataset_type: val
      data_root_dir: /root/autodl-tmp/data/ccac/track2/angle/
      data_file_path: 
      - val_data.json
      processor_ids:
      - IdProcessor
      - TextProcessor
      use_argument_cls: true
  # - dataset_type: inference
  #   data_root_dir: /root/autodl-tmp/data/imdb
  #   data_file_path: 
  #   - test.json
  #   processor_ids:
  #   - IdProcessor
    
model:
  class_name: T5Model
  module_path: ccac.models.t5_model
  config:
    auto_net:
      auto_net_path: /root/autodl-tmp/model/ccac/track2/mengzi
      auto_net_config: {}
    max_length: 64
    num_beams: 20
    # synced_gpus: false
    repetition_penalty: 5.0
    add_prompt: true
run_param:
  run_type: train
  log_dir: /root/autodl-tmp/save/hnu-nlp/ccac/track2/prompt/logs/
  log_level: info
  timer_type: all
  cuda_idx: 0
  seed: 42
  dataloader:
    train:
      batch_size: 16
      shuffle: true
    val:
      batch_size: 1
      shuffle: true
  meter:
    module_path: ccac.utils.ccac_meter
    class_name: Track2Meter
  train_param:
    max_epoch: 3
    log_interval: 20
    val_on_val_set: true     # 验证集上测试
    val_on_train_set: false   # 训练集上测试
    # ema:
    #   config: {}
    # fgm:
    #   config:
    #     embed_name: shared
    #     epsilon: 0.125
    optimizer:
      optimizer_name: adamw  # 原来使用的是adamw优化器，并且还有权重衰减。并且一部分有衰减，另一部分没有衰减，这个功能没有实现
      optimizer_config:
        weight_decay: 0.001
      use_warmup: true
      warmup_iter: 100
      lr: 0.0001
      # gradient_accumulation_steps: 1
      # lr_strategy: linear
      # start_epoch: 1
      # end_epoch: 20
      # min_lr: 0
      # lr_strategy: step
      # lr_step:
      # - 100000
    loss:
      class_name: OutLoss
      # class_name: LabelSmootherLoss
      module_path: common.losses
      config:
        label_smoothing_factor: 0.1
    checkpoint:
      ckpt_dir: /root/autodl-tmp/save/hnu-nlp/ccac/track2/prompt/model/
      save_by_epoch: false
      save_interval: 1
      save_best: false
      save_last: false
  val_param: {}
  inference_param:
    out_path: /root/autodl-tmp/save/hnu-nlp/mid/base_large/stage2/add/out/prediction.csv