load_yml_path: mid/configs/stage2/large_add.yml


model:
  config:
    auto_net:
      auto_net_path: /root/autodl-tmp/save/hnu-nlp/mid/pretrain/stage2/pad_large/pretrained_bart/best9088/

# run_param:
#   resume_file: /root/autodl-tmp/save/hnu-nlp/mid/base_large/stage2/model/epoch_best_2152.ckpt
  # train_param:
    # optimizer:
#       lr_strategy: step
#       lr_step:
#       - 11
